import { createConfig } from "@tokenami/css";

const BASE_FONT_SIZE = 16;
const BASE_GRID_SIZE = 4;
const BP_SM = 640;
const BP_MD = 768;
const BP_LG = 1024;
const BP_XL = 1280;
const BP_2XL = 1536;

const rem = <T extends number>(value: T) =>
    `${value / BASE_FONT_SIZE}rem` as const;
const remBreakpoint = <T extends number>(bp: T) =>
    `@media (min-width: ${rem(bp)})` as const;

const font = <S extends string, L extends string>(fontSize: S, lineHeight: L) =>
    `var(--font-stretch) var(--font-style) var(--font-variant) var(--font-weight) ${fontSize}/${lineHeight} var(--font-family)` as const;

const fluid = <
    P extends string,
    MinPx extends number,
    MaxPx extends number,
>(params: {
    property: P;
    from: MinPx;
    to: MaxPx;
    divider?: number;
}) => {
    const divider = params.divider ?? BASE_GRID_SIZE;
    const breakpointMin = params.from / BASE_FONT_SIZE;
    const breakpointMax = params.to / BASE_FONT_SIZE;
    const breakpointScope = breakpointMax - breakpointMin;
    return `
    clamp(calc(var(---${params.property}-min) * 1rem), calc((var(---${params.property}-scope) * 100vw) + (var(---${params.property}-intercept) * 1rem)), calc(var(---${params.property}-max) * 1rem));
    ---${params.property}-min: var(--${params.property}-min) / ${divider};
    ---${params.property}-max: var(--${params.property}-max) / ${divider};
    ---${params.property}-scope: (var(---${params.property}-max) - var(---${params.property}-min)) / ${breakpointScope};
    ---${params.property}-intercept: calc(var(---${params.property}-min) - (var(---${params.property}-scope) * ${breakpointMin}));
  ` as const;
};

export default createConfig({
    globalStyles: {
        "*, *::before, *::after": {
            boxSizing: "border-box",
        },
        body: {
            fontFamily: "system-ui, sans-serif",
            lineHeight: 1.5,
            margin: 0,
            padding: 0,
        },
    },
    include: ["./src/**/*.{ts,tsx}"],
    grid: "0.25rem",
    responsive: {},
    themeSelector: (mode) => (mode === "root" ? ":root" : `.theme-${mode}`),
    theme: {
        modes: {
            light: {
                color: {
                    bg: "oklch(0.97 0.0011 17.18)",
                    "text-main": "oklch(0.25 0.1423 274.12)",
                },
            },
            dark: {
                color: {
                    bg: "oklch(0.34 0.0555 288.82)",
                    "text-main": "oklch(0.87 0.0182 300.03)",
                },
            },
        },
        root: {
            alpha: {},
            anim: {},
            border: {
                rpsButton: "solid 0.25rem white",
            },
            color: { white: "#ffffff", pink: "oklch(0.88 0.0606 19.63)" },
            ease: {},
            font: {},
            "font-size": {
                huge: "3rem",
            },
            leading: {},
            "line-style": {},
            radii: {
                xs: "0.125rem",
                sm: "0.25rem",
                md: "0.375rem",
                lg: "0.5rem",
                xl: "0.75rem",
                "2xl": "1rem",
                full: "calc(infinity * 1px)",
                none: "0",
            },
            size: {
                "0": 0,
                px: rem(1),
                auto: "auto",
                fit: "fit-content",
                full: "100%",
                half: "50%",
                third: "33.333333%",
                "two-thirds": "66.666667%",
                quarter: "25%",
                "three-quarters": "75%",
                min: "min-content",
                max: "max-content",
                "screen-w": "100vw",
                "screen-h": "100vh",
                dvh: "100dvh",
                dvw: "100dvw",
                svh: "100svh",
                svw: "100svw",
                lvh: "100lvh",
                lvw: "100lvw",
            },
            shadow: {
                xl: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
            },
            surface: {},
            tracking: {},
            transition: {},
            weight: {},
            z: { "2": 2 },
            "text-size": {
                xs: rem(12),
                sm: rem(14),
                base: rem(16),
                lg: rem(18),
                xl: rem(20),
                "2xl": rem(24),
                "3xl": rem(30),
                "4xl": rem(36),
                "5xl": rem(48),
                "6xl": rem(60),
                "7xl": rem(72),
                "8xl": rem(96),
                "9xl": rem(128),
            },
            "fluid-text-size": {
                xs: 12 / BASE_FONT_SIZE,
                sm: 14 / BASE_FONT_SIZE,
                base: 16 / BASE_FONT_SIZE,
                lg: 18 / BASE_FONT_SIZE,
                xl: 20 / BASE_FONT_SIZE,
                "2xl": 24 / BASE_FONT_SIZE,
                "3xl": 30 / BASE_FONT_SIZE,
                "4xl": 36 / BASE_FONT_SIZE,
                "5xl": 48 / BASE_FONT_SIZE,
                "6xl": 60 / BASE_FONT_SIZE,
                "7xl": 72 / BASE_FONT_SIZE,
                "8xl": 96 / BASE_FONT_SIZE,
                "9xl": 128 / BASE_FONT_SIZE,
            },
            "fluid-text-size-clamp": {
                "min-max": fluid({
                    property: "fluid-text-size",
                    from: BP_SM,
                    to: BP_2XL,
                    divider: 1,
                }),
                "sm-md": fluid({
                    property: "fluid-text-size",
                    from: BP_SM,
                    to: BP_MD,
                    divider: 1,
                }),
                "sm-lg": fluid({
                    property: "fluid-text-size",
                    from: BP_SM,
                    to: BP_LG,
                    divider: 1,
                }),
                "sm-xl": fluid({
                    property: "fluid-text-size",
                    from: BP_SM,
                    to: BP_XL,
                    divider: 1,
                }),
                "md-lg": fluid({
                    property: "fluid-text-size",
                    from: BP_MD,
                    to: BP_LG,
                    divider: 1,
                }),
                "md-xl": fluid({
                    property: "fluid-text-size",
                    from: BP_MD,
                    to: BP_XL,
                    divider: 1,
                }),
                "md-2xl": fluid({
                    property: "fluid-text-size",
                    from: BP_MD,
                    to: BP_2XL,
                    divider: 1,
                }),
                "lg-xl": fluid({
                    property: "fluid-text-size",
                    from: BP_LG,
                    to: BP_XL,
                    divider: 1,
                }),
                "lg-2xl": fluid({
                    property: "fluid-text-size",
                    from: BP_LG,
                    to: BP_2XL,
                    divider: 1,
                }),
            },
        },
    },
    aliases: {
        bg: ["background-color"],
        h: ["block-size"],
    },
    selectors: {
        after: "&::after",
        before: "&::before",
        even: "&:nth-child(even)",
        odd: "&:nth-child(odd)",
        "first-child": "&:first-child",
        "last-child": "&:last-child",
        placeholder: "&::placeholder",
        hover: "&:hover",
        focus: "&:focus",
        "focus-visible": "&:focus-visible",
        "focus-within": "&:focus-within",
        active: "&:active",
        disabled: "&:disabled",
    },
    properties: {
        "accent-color": ["color"],
        animation: ["anim"],
        "animation-timing-function": ["ease"],
        background: ["color", "surface"],
        "background-color": ["color"],
        "background-image": ["surface"],
        "background-position": ["grid"],
        "background-position-x": ["grid"],
        "background-position-y": ["grid"],
        "block-size": ["grid", "size"],
        border: ["border"],
        "border-block": ["border"],
        "border-block-color": ["color"],
        "border-block-end": ["border"],
        "border-block-end-color": ["color"],
        "border-block-end-style": ["line-style"],
        "border-block-start": ["border"],
        "border-block-start-color": ["color"],
        "border-block-start-style": ["line-style"],
        "border-block-style": ["line-style"],
        "border-bottom": ["border"],
        "border-bottom-color": ["color"],
        "border-bottom-left-radius": ["radii"],
        "border-bottom-right-radius": ["radii"],
        "border-bottom-style": ["line-style"],
        "border-color": ["color"],
        "border-end-end-radius": ["radii"],
        "border-end-start-radius": ["radii"],
        "border-inline": ["border"],
        "border-inline-color": ["color"],
        "border-inline-end": ["border"],
        "border-inline-end-color": ["color"],
        "border-inline-end-style": ["line-style"],
        "border-inline-start": ["border"],
        "border-inline-start-color": ["color"],
        "border-inline-start-style": ["line-style"],
        "border-inline-style": ["line-style"],
        "border-left": ["border"],
        "border-left-color": ["color"],
        "border-left-style": ["line-style"],
        "border-radius": ["radii"],
        "border-right": ["border"],
        "border-right-color": ["color"],
        "border-right-style": ["line-style"],
        "border-start-end-radius": ["radii"],
        "border-start-start-radius": ["radii"],
        "border-style": ["line-style"],
        "border-top": ["border"],
        "border-top-color": ["color"],
        "border-top-left-radius": ["radii"],
        "border-top-right-radius": ["radii"],
        "border-top-style": ["line-style"],
        bottom: ["grid"],
        "box-shadow": ["shadow"],
        "caret-color": ["color"],
        color: ["color"],
        "column-gap": ["grid"],
        "column-rule-color": ["color"],
        "column-rule-width": ["grid"],
        "column-width": ["grid", "size"],
        fill: ["color"],
        "flex-basis": ["grid", "size"],
        "font-family": ["font"],
        "font-size": ["text-size", "fluid-text-size-clamp"],
        "font-weight": ["weight"],
        gap: ["grid"],
        height: ["grid", "size"],
        "inline-size": ["grid", "size"],
        inset: ["grid"],
        "inset-block": ["grid"],
        "inset-block-end": ["grid"],
        "inset-block-start": ["grid"],
        "inset-inline": ["grid"],
        "inset-inline-end": ["grid"],
        "inset-inline-start": ["grid"],
        left: ["grid"],
        "letter-spacing": ["tracking"],
        "line-height": ["leading"],
        margin: ["grid"],
        "margin-block": ["grid"],
        "margin-block-end": ["grid"],
        "margin-block-start": ["grid"],
        "margin-bottom": ["grid"],
        "margin-inline": ["grid"],
        "margin-inline-end": ["grid"],
        "margin-inline-start": ["grid"],
        "margin-left": ["grid"],
        "margin-right": ["grid"],
        "margin-top": ["grid"],
        "max-block-size": ["grid", "size"],
        "max-height": ["grid", "size"],
        "max-inline-size": ["grid", "size"],
        "max-width": ["grid", "size"],
        "min-block-size": ["grid", "size"],
        "min-height": ["grid", "size"],
        "min-inline-size": ["grid", "size"],
        "min-width": ["grid", "size"],
        opacity: ["alpha"],
        "outline-color": ["color"],
        padding: ["grid"],
        "padding-block": ["grid"],
        "padding-block-end": ["grid"],
        "padding-block-start": ["grid"],
        "padding-bottom": ["grid"],
        "padding-inline": ["grid"],
        "padding-inline-end": ["grid"],
        "padding-inline-start": ["grid"],
        "padding-left": ["grid"],
        "padding-right": ["grid"],
        "padding-top": ["grid"],
        right: ["grid"],
        "row-gap": ["grid"],
        "scroll-margin": ["grid"],
        "scroll-margin-bottom": ["grid"],
        "scroll-margin-left": ["grid"],
        "scroll-margin-right": ["grid"],
        "scroll-margin-top": ["grid"],
        "scroll-padding": ["grid"],
        "scroll-padding-bottom": ["grid"],
        "scroll-padding-left": ["grid"],
        "scroll-padding-right": ["grid"],
        "scroll-padding-top": ["grid"],
        stroke: ["color"],
        "text-decoration-color": ["color"],
        "text-shadow": ["shadow"],
        top: ["grid"],
        transition: ["transition"],
        "transition-timing-function": ["ease"],
        width: ["grid", "size"],
        "z-index": ["z"],
    },
    customProperties: {
        "fluid-text-size-min": ["fluid-text-size"],
        "fluid-text-size-max": ["fluid-text-size"],
    },
});
