/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ApiSplatImport } from './routes/api/$'
import { Route as GameRpsIndexImport } from './routes/game/rps/index'
import { Route as GameRpsRoomIdImport } from './routes/game/rps/$roomId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ApiSplatRoute = ApiSplatImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRoute,
} as any)

const GameRpsIndexRoute = GameRpsIndexImport.update({
  id: '/game/rps/',
  path: '/game/rps/',
  getParentRoute: () => rootRoute,
} as any)

const GameRpsRoomIdRoute = GameRpsRoomIdImport.update({
  id: '/game/rps/$roomId',
  path: '/game/rps/$roomId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatImport
      parentRoute: typeof rootRoute
    }
    '/game/rps/$roomId': {
      id: '/game/rps/$roomId'
      path: '/game/rps/$roomId'
      fullPath: '/game/rps/$roomId'
      preLoaderRoute: typeof GameRpsRoomIdImport
      parentRoute: typeof rootRoute
    }
    '/game/rps/': {
      id: '/game/rps/'
      path: '/game/rps'
      fullPath: '/game/rps'
      preLoaderRoute: typeof GameRpsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/game/rps/$roomId': typeof GameRpsRoomIdRoute
  '/game/rps': typeof GameRpsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/game/rps/$roomId': typeof GameRpsRoomIdRoute
  '/game/rps': typeof GameRpsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/game/rps/$roomId': typeof GameRpsRoomIdRoute
  '/game/rps/': typeof GameRpsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/$' | '/game/rps/$roomId' | '/game/rps'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/$' | '/game/rps/$roomId' | '/game/rps'
  id: '__root__' | '/' | '/api/$' | '/game/rps/$roomId' | '/game/rps/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSplatRoute: typeof ApiSplatRoute
  GameRpsRoomIdRoute: typeof GameRpsRoomIdRoute
  GameRpsIndexRoute: typeof GameRpsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSplatRoute: ApiSplatRoute,
  GameRpsRoomIdRoute: GameRpsRoomIdRoute,
  GameRpsIndexRoute: GameRpsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/api/$",
        "/game/rps/$roomId",
        "/game/rps/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/api/$": {
      "filePath": "api/$.tsx"
    },
    "/game/rps/$roomId": {
      "filePath": "game/rps/$roomId.tsx"
    },
    "/game/rps/": {
      "filePath": "game/rps/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
