/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as GameRpsIndexRouteImport } from './routes/game/rps/index'
import { Route as GameRpsRoomIdRouteImport } from './routes/game/rps/$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRpsIndexRoute = GameRpsIndexRouteImport.update({
  id: '/game/rps/',
  path: '/game/rps/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRpsRoomIdRoute = GameRpsRoomIdRouteImport.update({
  id: '/game/rps/$roomId',
  path: '/game/rps/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/game/rps/$roomId': typeof GameRpsRoomIdRoute
  '/game/rps': typeof GameRpsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/game/rps/$roomId': typeof GameRpsRoomIdRoute
  '/game/rps': typeof GameRpsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/game/rps/$roomId': typeof GameRpsRoomIdRoute
  '/game/rps/': typeof GameRpsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/$' | '/game/rps/$roomId' | '/game/rps'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/$' | '/game/rps/$roomId' | '/game/rps'
  id: '__root__' | '/' | '/api/$' | '/game/rps/$roomId' | '/game/rps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSplatRoute: typeof ApiSplatRoute
  GameRpsRoomIdRoute: typeof GameRpsRoomIdRoute
  GameRpsIndexRoute: typeof GameRpsIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/rps/': {
      id: '/game/rps/'
      path: '/game/rps'
      fullPath: '/game/rps'
      preLoaderRoute: typeof GameRpsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/rps/$roomId': {
      id: '/game/rps/$roomId'
      path: '/game/rps/$roomId'
      fullPath: '/game/rps/$roomId'
      preLoaderRoute: typeof GameRpsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSplatRoute: ApiSplatRoute,
  GameRpsRoomIdRoute: GameRpsRoomIdRoute,
  GameRpsIndexRoute: GameRpsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
